export const routes = {
    home: 'home',
    login: 'login',
    logout: 'logout',
    signUp: 'sign-up',
    initial: 'initial',
    search: 'search',
    passwordResetSuccess: 'password-reset-success',
    codeVerify: 'code-verify',
    newPassword: 'new-password',
    onboarding: 'onboarding',
    account: 'account',
    accountTab: 'account-tab',
    busTicket: 'bus-ticket',
    updatebus: 'updatebus',
    registerBus: 'register-bus',
    addSeat: 'add-seat',
    changePassword: 'change-password',
    downloadTicket: 'download-ticket',
    getStarted: 'get-started',
    forgotPassword: 'forgot-password',
    dashboard: 'dashboard',
    dashboardTab: 'dashboard-tab',
    report: 'report',
    reportTab: 'report-tab',
    qrCode: 'qr-code',
    qrCodeTab: 'qr-code-tab',
    notification: 'notification',
    notificationTab: 'notification-tab',
    buslisting: 'bus-listing',
    selectSeat: 'select-seat',
    passengerInfo: 'passenger-info',
    confirmDetails: 'confirm-details',
    completePayment: 'complete-payment',
    paymentStatus: 'payment-status',
    ticketDetails: 'ticket-details',
    bookedTicket: 'booked-ticket',
    userProfile: 'user-profile',
    contact: 'contact',
    history: 'history',
    payment: 'payment',
  
    //Screens
    ticketScreen: 'ticket-screen',
    accountScreen: 'account-screen',
    contactScreen: 'contact-screen',
    historyScreen: 'history-screen',
    bookedTicketScreen: 'booked-ticket-screen',
  };
  